config_pyiot:
  mqtt:
    server_url: "broker.mqttdashboard.com"           # http://www.hivemq.com/demos/websocket-client/
    server_port:  1883
    topic_sub: "eyrc/ThRaAdAs/iot_to_ros"
    topic_pub: "eyrc/ThRaAdAs/ros_to_iot"
    qos: 0

    sub_cb_ros_topic:  "/ros_iot_bridge/mqtt/sub"
  google_apps:
    spread_sheet_id: 'AKfycbwXzjtKrr7XGOKF5y7BiaVnSrwnqsd2Ot-AGsdzx127XPIz4PnP'
